### ISSUE TITLE
Citing GBIF data

### ISSUE THREAD

**Issue by dnoesgaard** [tts/asianelephants#1]
Hi there (I work for GBIF),

Cool project! I just wanted to reach out to ensure that you are aware of the GBIF terms of use for occurrence data, specifically, that we require that data publishers are credited. Happy to discuss ways how that might work in your project!

Is the GBIF data presented on https://ttso.shinyapps.io/asianelephants/ static or refreshed every time a user loads the app?

Look forward to hearing from you.

**Comment by tts** [comment]
Hi Daniel, and thanks for the reminder! 

From [iNaturalist help](https://www.inaturalist.org/pages/help#cite) I understand that their choice #1 is to use a derived dataset with a DOI. However, I'm not sure how to accomplish this with the rgbif R library because in my code I don't use the _occ_download_ function but _occ_search_. 

GBIF data in this app is static. I have now updated the landing page with a general iNaturalist citation. Would that be enough in my case?

**Comment by dnoesgaard** [comment]
If your data is static, I would recommend a derived dataset. This is a rather new service, so it's not available in R yet. But you simply need to summarize your data based on the column `datasetKey` to get a list of the contributing datasets and how many records each contributed. Using this, you can create the derived dataset here: https://www.gbif.org/derived-dataset/register

I'm also happy to help, just let me know!

**Comment by tts** [comment]
Thanks for the advice! I have now done the dataset, and added the DOI to the app info as citation.

For some reason however, the markup in my description field did not work as expected so the rendition of the result is broken. I wonder if you could help? I couldn't find a way to edit the text after submitting it. And even if I could, I'm not sure whether the markup (editor) would work this time either. FYI, I used Chrome on Windows.

**Comment by dnoesgaard** [comment]
Great, thanks!

I don't actually think that markup is intended, so I'll have a word with our developers to fix that. In the mean time, I'll see what I can do about cleaning up yours.

**Comment by dnoesgaard** [comment]
Ok, I removed the markup from the description now. I've also linked the dataset record to a internal record of the app which in turn means that each of the 21 contributing dataset now have a citation from your app :)

Btw, I see that you've provided a link to the summary in the derived dataset. But the idea is actually to provide a link to the actual data for anyone who wants to re-use it. So if the file `data/el.RDS` is available, this is what we should be linking to.

**Comment by dnoesgaard** [comment]
I was too fast! The rich text is now rendered properly on the derived dataset page, so I changed it back :)

**Comment by tts** [comment]
Can I still bother you? Could you please change the link to this one: https://github.com/tts/asianelephants/blob/main/data/el.RDS

**Comment by dnoesgaard** [comment]
Done!

While we don't yet have UI for this, you can make changes yourself by doing an basic authenticated HTTP PUT request with a JSON payload e.g. 

```
curl --location --request PUT 'https://api.gbif.org/v1/derivedDataset/10.15468/dd.vwcmpu' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic <base64 string encoding your GBIF username/password>' \
--data-raw '{
  "title": "Asian Elephant observations",
  "sourceUrl": "https://github.com/tts/asianelephants/blob/main/data/el.RDS",
  "description": "The dataset was derived with the *rgbif* R library by first using the function *occ_search()* and then filtering those rows which were considered bad data in this case, meaning the coordinates were not within Asia, and the column acceptedScientificName was not a name. The relevant rows of code start [here](https://github.com/tts/asianelephants/blob/main/preparedata.R#L13)."
}'
```

**Comment by dnoesgaard** [comment]
And btw, a big thanks for your help on this!

**Comment by tts** [comment]
No problem at all, thanks yourself for being active and contacting me! Only now do I understand the importance of proper citation in this case.
